[package]
name = "floating-ui-core"
description = "Rust port of Floating UI. Positioning library for floating elements: tooltips, popovers, dropdowns, and more."
homepage = "https://floating-ui.rustforweb.org"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
dyn-clone.workspace = true
dyn_derive = "0.3.4"
dyn_std = "0.3.3"
floating-ui-utils = { path = "../utils", version = "0.0.9" }
serde.workspace = true
serde_json.workspace = true
